ISISComputingGroup/EPICS-inst_servers

BlockServer/block_server.py
BlockServer/core/synoptic_manager.py

Refers to issue ISISComputingGroup/ICP/issues/2

Ticket 832 add blank synoptic

---

BlockServer/block_server.py
BlockServer/blockserver_docs/block_server.rst
BlockServer/blockserver_docs/configuration_rules.rst

Moved save and set config to run on a thread

Ticket 904: When editing current config, saving, and editing again values do not update

---

DatabaseServer/exp_data.py

To test:
* Add a user with a multi-worded surname e.g. "van der Graff"
* Confirm that 'Graff' is the name that appears on the dashboard, rather than 'van'

Surname is now assumed to be the last name of a fullname

---

BlockServer/config/containers.py

Pull requests in other modules needed to test this, see issue: ISISComputingGroup/ICP#3

Change to blockserver to server up run control settings on blocks

---

BlockServer/epics/gateway.py

To test, caget a run control PV and check that you do not get multiple PV replies

Exclude :RC: run conrol PVs from aliasing

---

BlockServer/block_server.py
BlockServer/core/config_holder.py
BlockServer/core/config_list_manager.py
BlockServer/core/synoptic_manager.py
BlockServer/fileIO/config_file_event_handler.py
BlockServer/fileIO/file_manager.py
BlockServer/fileIO/schema_checker.py
BlockServer/fileIO/synoptic_file_event_handler.py
BlockServer/run_tests.py
BlockServer/test_modules/file_event_handler_tests.py
BlockServer/test_modules/schema_checker_tests.py
BlockServer/test_modules/synoptic_manager_tests.py
DatabaseServer/database_server.py
DatabaseServer/run_tests.py
DatabaseServer/test_modules/mysql_wrapper_tests.py

replace use of \\ with  os.path.join()  and  os.sep

Fix paths for use on Linux

---

BlockServer/block_server.py
BlockServer/core/active_config_holder.py
BlockServer/core/config_holder.py
BlockServer/core/config_list_manager.py
BlockServer/core/constants.py
BlockServer/core/synoptic_manager.py
BlockServer/fileIO/config_file_event_handler.py
BlockServer/fileIO/file_manager.py
BlockServer/fileIO/file_watcher_manager.py
BlockServer/fileIO/schema_checker.py
BlockServer/test_modules/config_list_manager_tests.py
BlockServer/test_modules/file_event_handler_tests.py
BlockServer/test_modules/schema_checker_tests.py
start_blockserver_cmd.bat

To test:
* Delete/rename your synoptics folder
* Start the blockserver
* Confirm that the blockserver has started and that a new synoptics folder exists

Corrected path to synoptics folder

---

BlockServer/block_server.py
BlockServer/core/ioc_control.py

To test:
* Create a config with an IOC set to auto-restart (e.g. TPG300_01).
* Set a monitor on the IOC's restart PV (camonitor %MYPVPREFIX%CS:PS:TPG300_01:AUTORESTART
* Open the start/stop IOCs dialog via the GUI.
* Stop the IOC and check AUTORESTART is Off
* Start the IOC and check that AUTORESTART is reset to Off
Repeat for an IOC that is isn't set to auto-restart and check AUTORESTART stays Off throughout.

Ticket #1029: Reapplies the auto-restart setting if a IOC is stopped and started

---

DatabaseServer/database_server.py
DatabaseServer/ioc_data.py
DatabaseServer/test_modules/mysql_wrapper_tests.py

See https://github.com/ISISComputingGroup/ICP/issues/4

Add ways of looking at the facility pvs

---

start_blockserver.sh
start_blockserver_cmd.sh
start_database_server.sh
start_database_server_cmd.sh
stop_blockserver.sh
stop_database_server.sh

Added bash scripts for Linux startup and shutdown.

Add Linux start instance support

---

scripts/hex_compress_and_put_pv.py

Isabella wrote this script to avoid having to do separate hex and compress on PV values before setting them manually. Kind of handy, so I wanted it to be preserved. Previously contained in pull request:
https://github.com/ISISComputingGroup/ibex_gui/pull/209

Add Isabella's put PV script. 

---

BlockServer/block_server.py
BlockServer/run_tests.py
BlockServer/site_specific/default/block_rules.py
BlockServer/site_specific/default/general_rules.py
BlockServer/site_specific/default/group_rules.py
BlockServer/site_specific/default/test_modules/block_rules_tests.py
BlockServer/site_specific/default/test_modules/group_rules_tests.py

https://github.com/ISISComputingGroup/IBEX/issues/1146
Add group rules and correct block rules
This change is needed to test https://github.com/ISISComputingGroup/ibex_gui/pull/212

Ticket1146 validate group names

---

BlockServer/block_server.py

ISISComputingGroup/IBEX/issues/1186
I have also changed save new config and comp to be queued.

Ticket 1186: Added exception handling

---

BlockServer/core/config_list_manager.py

Fixed code with blockserver prefix added twice.
To test:
* Confirm unit tests run without failing

Fixed the failing build due to Ticket 1064

---

WebServer/simple_webserver.py

Fixes https://github.com/ISISComputingGroup/IBEX/issues/1427

Create simple python webserver

---

BlockServer/config/ioc.py
BlockServer/fileIO/file_manager.py
BlockServer/test_modules/ioc_class_tests.py

https://github.com/ISISComputingGroup/IBEX/issues/1462

Blockserver simlevel spelling

---

WebServer/simple_webserver.py
block_server.py

Shows relevant information on a web page.
To test:
* Start up instrument and navigate to localhost:8008 in a browser
* Confirm that the page updates when configs change (requires a refresh)

Dataweb: Blockserver now serves up current config on a URL

---

BlockServer/run_tests.py
BlockServer/spangle_banner/banner.py
BlockServer/test_modules/banner_tests.py

https://github.com/ISISComputingGroup/IBEX/issues/1498

Ticket1498 failing banner tests

---

schema/screens.xsd

For ticket https://github.com/ISISComputingGroup/IBEX/issues/1124

Schema makes names unique

---

BlockServer/epics/gateway.py

See ISISComputingGroup/IBEX#1574
To test, add a block from a motor with a .LLM field and check it gets a value OK rather than "error" shown in the block. You may need to edit your blocks.xml to do this as the GUI will not let you add a field.

Ticket1574 blocks field links

---

JSON_Bourne/My Website.html
JSON_Bourne/block.py
JSON_Bourne/display_blocks.js
JSON_Bourne/get_webpage.py
JSON_Bourne/webserver.py
block_server.py
start_json_bourne.bat
start_json_bourne.sh
start_json_bourne_cmd.bat
start_json_bourne_cmd.sh
stop_json_bourne.bat
stop_json_bourne.sh

Changed title of group for ungrouped blocks in dataweb from "None" to "Other" to match the title in the GUI.

Ticket1504 rename none group

---

BlockServer/fileIO/file_manager.py
BlockServer/fileIO/synoptic_file_event_handler.py
BlockServer/run_tests.py
ConfigVersionControl/config_version_control.py
ConfigVersionControl/constants.py
ConfigVersionControl/git_version_control.py
ConfigVersionControl/svn_version_control.py
ConfigVersionControl/vc_exceptions.py
ConfigVersionControl/version_control_wrapper.py
block_server.py
start_blockserver_cmd.bat
start_blockserver_cmd.sh

Fixes https://github.com/ISISComputingGroup/IBEX/issues/1379.
To test:
* Create a config and edit it
* Stop the instrument
* Clone your configuration branch into a new folder (see Setting up a configurations directory in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows))
* Confirm the configuration and edits are in the new folder
* Repeat with deleting configurations
* Repeat with synoptics

Moved ConfigVersionControl into inst_server

---

BlockServer/spangle_banner/banner.py

Changed hardcoded banner item used on LARMOR to point at correct PV
Fixes https://github.com/ISISComputingGroup/IBEX/issues/1628

pointing at correct PV

---

DatabaseServer/exp_data.py
DatabaseServer/ioc_data.py
DatabaseServer/mysql_abstraction_layer.py
DatabaseServer/test_modules/exp_data_test.py
DatabaseServer/test_modules/mysql_wrapper_tests.py

Use connection based pool name

---

BlockServer/core/config_list_manager.py
BlockServer/core/config_list_manager_exceptions.py
BlockServer/synoptic/synoptic_exceptions.py
BlockServer/synoptic/synoptic_manager.py
ConfigVersionControl/git_version_control.py
block_server.py

I've updated the handling of exceptions arising from issues associated with version control. These are now caught and logged. Notably the fix for #1518 means that uncaught exceptions no longer cause threads to crash the block server.
I don't think we can control what happens with the block server on shutdown as it can come from a range of sources. I've added a method to try and unlock the repo on startup. If the repo is indeed locked by some external process, the lock should be locked by the process that owns it. If we can remove the lock so simply, then it's an artefact of a process that's already exit. For now I've just done this on startup.
https://github.com/ISISComputingGroup/IBEX/issues/1673
Test that the add/edit/remove operations work for each of …

Ticket1673 handle git lock crashes

---

.gitignore

Make Git ignore the .idea folder generated by PyCharm for inst_servers.
https://github.com/ISISComputingGroup/IBEX/issues/1701
.idea folder not flagged as a change by Git when inst_server opened as a project in PyCharm
---

Add .idea folder (PyCharm) to .gitignore

---

BlockServer/fileIO/file_manager.py

Updated the import to use the correct module
#1862
You can start the blockserver with no issues
---

Update the source of the version control

---

BlockServer/config/ioc.py
block_server.py

Update the documentation describing IOC behaviour
https://github.com/ISISComputingGroup/IBEX/issues/1788
IOC documentation makes sense and matches actual behaviour
---

Update IOC documentation

---

DatabaseServer/database_server.py

Incorrect change made in #1751 which has been merged, Undo that change.
database server works correctly.
---

Revert change to database server use correct method

---

DatabaseServer/ioc_data.py

Pass the IOC description along with the IOC information to the GUI so it can be displayed
https://github.com/ISISComputingGroup/IBEX/issues/2048
IOC information is transferred to the client for all IOCs. See related PRs in other repos
---

Query IOC descriptions from database

---

scripts/set_instrument_list.py

Add POLARIS to the instruments list.
https://github.com/ISISComputingGroup/IBEX/issues/2252
---

Ticket2252: Added Polaris to instrument list

---

scripts/set_instrument_list.py

Add Vesuvio to the instruments list.
https://github.com/ISISComputingGroup/IBEX/issues/2274
---

Add Vesuvio to instrument list

---

BlockServer/test_modules/config_file_event_handler_tests.py
BlockServer/test_modules/devices_manager_tests.py
BlockServer/test_modules/file_path_manager_tests.py
BlockServer/test_modules/schema_checker_tests.py

This PR fixes the blockserver unit tests which I broke in ticket 2134

Fix blockserver tests

---

BlockServer/test_modules/schema_checker_tests.py

Add better error on test fail for diagnosis

---

BlockServer/test_modules/schema_checker_tests.py

Better error on xml problem

---

DatabaseServer/database_server.py
DatabaseServer/run_tests.py
DatabaseServer/test_modules/database_server_test_mysql.py
DatabaseServer/test_modules/options_holder_tests.py
server_common/ioc_data.py
server_common/test_modules/test_mysql_wrapper.py

Fix the build by editing tests
---

Fix tests and make them work

---

BlockServer/fileIO/schema_checker.py

lxml has two ways to validate schema, while initially reading
the file or post reading. Since updating lxml the validate as
read doesn't work, it looks like attributes were not read correctly.
While trying to check this, changing to a two step process seems
to fix it.
See ISISComputingGroup/IBEX#2502
The PR changes the method used to validate schema in the blockserver, so check that: 
* Units test still work on Windows
* Configuration reading/creating/saving gives no errors
---

Fix reading of schema with updated lxml

---

scripts/set_instrument_list.py

Add HRPD to the instruments list.
https://github.com/ISISComputingGroup/IBEX/issues/2248
---

Add HRPD to instrument dictionary

---

BlockServer/runcontrol/runcontrol_manager.py

Blockserver startup fails if it checks for the runcontrol start time before the runcontrol IOC has started. The conversion of the return value from the start time through an uncaught type error if the caget returned None.
https://github.com/ISISComputingGroup/IBEX/issues/2526
No failure on Blockserver startup
UI tests pass
---

Catch uncaught exception

---

ConfigVersionControl/git_version_control.py

Check if a file really needs adding to git
See ISISComputingGroup/IBEX#2574
See ISISComputingGroup/IBEX#2574
---

Check if file/directory really needs adding to git

---

ArchiverAccess/archiver_access.py

Increase time period
Check throughput is lessened
https://github.com/ISISComputingGroup/IBEX/issues/2672
Time is sensible
---

Increase time between polling database

---

ConfigVersionControl/git_message_provider_tests.py

Fix unit tests that were failing due to case issues on Linux
https://github.com/ISISComputingGroup/IBEX/issues/2624
The build passes without errors
---

Change file paths in tests to expected lowercase

---

BlockServerToKafka/main.py
BlockServerToKafka/run_tests.py
Jenkinsfile

Added BlockserverToKafka tests to pipeline
Confirm that Jankins automatically runs the BlockserverToKafka tests and they pass.
Not code so most normal criteria not applicable.
---

Add BlockserverToKafka tests to pipeline

---

BlockServer/core/active_config_holder.py
BlockServer/core/on_the_fly_pv_interface.py
BlockServer/devices/devices_manager.py
BlockServer/epics/gateway.py
BlockServer/mocks/mock_archiver_wrapper.py
BlockServer/mocks/mock_ioc_control.py
BlockServer/runcontrol/runcontrol_manager.py
BlockServer/synoptic/synoptic_manager.py
BlockServer/test_modules/test_active_config_holder.py
BlockServer/test_modules/test_devices_manager.py
BlockServer/test_modules/test_runcontrol_manager.py
block_server.py

Don't restart gateway, runcontrol, or archiver if they don't need to be
restarted.
Only restart an IOC when it has been changed.
https://github.com/ISISComputingGroup/IBEX/issues/3089
Test to make sure GWBLOCK, RUN, ARBLOCK only restart when appropriate (When changes have been made to a block in Ibex->Configuration->Edit Current Configuration.
Test to make sure IOCs only restart when they have been modified in Ibex->Configuration->Edit Current Configuration.
Test to make sure nothing restarts when making cosmetic changes to the configuration (changing Description).
To see if something is restarting, open an EPICS terminal and run console -M localhost [IOCNAME]
Make changes in Ibex GUI and see if anything appears in the console.
GWBLOCK: message says "Reading access security files"
RUN: …

Ticket 3089: Check for changes to blocks when saving config

---

ConfigVersionControl/git_version_control.py

Ensures that the branch is checked each time against allowed branches, not just once at startup.
https://github.com/ISISComputingGroup/IBEX/issues/3272
- Follow the workflow in original ticket: changes to not get pushed
---

Better logic to tell if pushing to wrong branch

---

server_common/utilities.py

Get rid of len error and other PEP8 errors

---

ReflectometryServer/ChannelAccess/pv_manager.py
ReflectometryServer/ChannelAccess/reflectometry_driver.py
ReflectometryServer/beamline.py
ReflectometryServer/beamline_configuration.py
ReflectometryServer/parameters.py
ReflectometryServer/reflectometry_server.py
ReflectometryServer/run_tests.py

* Added a PV holding tracking PVs read by the OPI. 
* Various refactoring in PV Manager
* Various little bits (updated docstrings, added supermirror pos to sim beamline, better parameter PV lookup)
For https://github.com/ISISComputingGroup/IBEX/issues/3494
---

Ticket3494 reflectometry opi

---

scripts/set_instrument_list.py

Add IRIS setup machine
https://github.com/ISISComputingGroup/IBEX/issues/3673

Add IRIS Setup

---

scripts/set_instrument_list.py

Added OSIRIS to instlist PV.
https://github.com/ISISComputingGroup/IBEX/issues/3713

Added OSIRIS

---

scripts/set_instrument_list.py

Adds LOQ to instrument list
https://github.com/ISISComputingGroup/IBEX/issues/3461
---

Add LOQ to inst list

---

.coveragerc
BlockServer/test_modules/test_configuration.py
Jenkinsfile
run_all_tests.py

Adds code coverage metrics in Jenkins.
Confirm that the code coverage is displayed in Jenkins,
---

Added code coverage

---

Jenkinsfile

Move when outside

---

ReflectometryServer/pv_wrapper.py
server_common/channel_access.py

Add vertical jaws wrapper needed for slit 3 on crisp

---

ReflectometryServer/__init__.py
ReflectometryServer/test_modules/test_config/error_config/refl/config.py
ReflectometryServer/test_modules/test_config/good_config/refl/config.py

Make a central place for importing components needed in config.

Create single import place for all modules needed for config

---

scripts/log_file_generator.py

Enable getting data from central archive

Log file added

---

BlockServer/runcontrol/runcontrol_manager.py

https://github.com/ISISComputingGroup/IBEX/issues/4344

Mitigate against race condition

---

ReflectometryServer/ChannelAccess/reflectometry_driver.py

Init mode when adding listener on mode

---

ReflectometryServer/file_io.py

Changed mkdir to makedirs so that non-existent directories in the filepath are created recursively (rather than just the rightmost directory in the path).
Flash reviewed by @John-Holt-Tessella 
Fixes Redhat build
/
---

change mkdir to makedirs

---

BlockServerToKafka/kafka_producer.py

See https://github.com/ISISComputingGroup/IBEX/issues/4464
* Start the following script with your machine name as the instrument:
``` python
from kafka import KafkaConsumer
KAFKA_SERVER = "tenten.isis.cclrc.ac.uk:9092"
INSTRUMENT = "NDXDEMO"
consumer = KafkaConsumer(INSTRUMENT + "_sampleEnv", bootstrap_servers=[KAFKA_SERVER])
for message in consumer:
print ("{}:{}:{}: key={} value={}".format(message.topic, message.partition,
message.offset, message.key,
message.value))
```
* Start your IBEX server
* Confirm that any blocks you have are printed in the python console
* Change a block name, confirm that the new block is printed
* Change the value of a block and confirm a new message is printed (Note that the value of the block is stored in Kafka as a binary format and so isn't readable using …

Ticket 4464: Corrected topic URI for blockserver to kafka

---

scripts/set_instrument_list.py

Adds nimrod to the instrument list

Add nimrod to instrument list

---

ReflectometryServer/ChannelAccess/pv_manager.py
ReflectometryServer/ChannelAccess/reflectometry_driver.py

Changed MOVE terminology for generic PV's to ACTION
[#4322](https://github.com/ISISComputingGroup/IBEX/issues/4322)
---

Ticket 4322: Change MOVE to ACTION

---

scripts/set_instrument_list.py

Added DETMON to the set_instrument_list.py file
[4181](https://github.com/ISISComputingGroup/IBEX/issues/4181)
None, only flash review required
---
Only flash review required according to:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Making-an-Instrument-Available-from-the-GUI

Adding DETMON to instrument list

---

ReflectometryServer/ChannelAccess/constants.py
ReflectometryServer/ChannelAccess/pv_manager.py
ReflectometryServer/ChannelAccess/reflectometry_driver.py
ReflectometryServer/__init__.py
ReflectometryServer/beam_path_calc.py
ReflectometryServer/beamline.py
ReflectometryServer/beamline_configuration.py
ReflectometryServer/engineering_corrections.py
ReflectometryServer/file_io.py
ReflectometryServer/footprint_calc.py
ReflectometryServer/ioc_driver.py
ReflectometryServer/movement_strategy.py
ReflectometryServer/observable.py
ReflectometryServer/parameters.py
ReflectometryServer/pv_wrapper.py
ReflectometryServer/reflectometry_server.py
ReflectometryServer/test_modules/data_mother.py
ReflectometryServer/test_modules/test_beamline.py
ReflectometryServer/test_modules/test_configuration.py
ReflectometryServer/test_modules/test_engineering_corrections.py
ReflectometryServer/test_modules/test_observable.py
server_common/test_modules/test_common_utilities.py
server_common/utilities.py

Add engineering corrections in line with wiki https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Composite-Driving-Layer#engineering-offset
https://github.com/ISISComputingGroup/IBEX/issues/3541
1. Check
1. correction
1. Constant correction
1. User Function Correction
1. Interpolated correction
1. for
1. move to position, motor moves to position + correction
1. readbacks don't include correction
1. Corrections and descriptions should appear on driver correction tab, listed by their axis.
1. On init, if the parameter is not autosaved correction should be 0 but an error should be logged.
1. Errors in user function should give a correction of 0 and should have that error logged.
---

Ticket3541 engineering corrections

---

ReflectometryServer/test_modules/test_beamline_parameter.py

Did rename in datamother of method but failed to refactor

Make name of method correct

---

CollisionAvoidanceMonitor/test_modules/__init__.py

Dont run CAM tests on linux

---

run_all_tests.py

Add verbosity

---

BlocksCache/blocks_cache.py

fix unicode vs str problem

---

RemoteIocServer/config_monitor.py
RemoteIocServer/test_modules/test_config_monitor.py
RemoteIocServer/utilities.py

Fix tests when genie_python not available

Move other genie python into try catch and remove unneeded references

---

ReflectometryServer/pv_wrapper.py

- Added space to eos since it joined with next string

Fix velocity set loggger message

---

BlockServer/test_modules/__init__.py

Block server tests are failing on rhel 6 build, remove them.
---

Skip linux build

---

ReflectometryServer/components.py
ReflectometryServer/test_modules/test_observable.py

Updates reference to observable
---

observable has moved

---

DatabaseServer/exp_data.py
DatabaseServer/test_modules/test_exp_data.py

See https://github.com/ISISComputingGroup/IBEX/issues/5140
* Follow steps on the original ticket
* Tests fail on master and pass on this branch
---

Ticket 5140: Allow setting RB number correctly

---

DatabaseServer/exp_data.py
DatabaseServer/test_modules/test_exp_data.py

As for master https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/268

Ticket5140 set rb number

---

ReflectometryServer/ChannelAccess/pv_manager.py
ReflectometryServer/ChannelAccess/reflectometry_driver.py
ReflectometryServer/__init__.py
ReflectometryServer/beamline.py
ReflectometryServer/beamline_configuration.py
ReflectometryServer/beamline_constant.py
ReflectometryServer/footprint_calc.py
ReflectometryServer/pv_wrapper.py
ReflectometryServer/test_modules/test_beamline.py
ReflectometryServer/test_modules/test_ioc_driving_layer.py
ReflectometryServer/value_parameter.py

Add values that can be exposed from the config
https://github.com/ISISComputingGroup/IBEX/issues/4331
Values can be set floats or bools and they are pvs.
---

Add values to the beamline

---

ReflectometryServer/ioc_driver.py

remove reference to genie python
---

Remove unneeded import

---

ReflectometryServer/beamline.py
ReflectometryServer/ioc_driver.py
ReflectometryServer/parameters.py
ReflectometryServer/pv_wrapper.py

Added additional logging:
- Log when a move is triggered
- Log when the active mode is changed and any param defaults applied
- Log whenever a Parameter SP RBV changes
- Log when a new SP is sent to a motor axis
- Log the quickest possible move for each moving axis (at debug level)
- Log the quickest overall move (at debug level)
Also investigated and fixed some bugs discovered through unexpected logging entries:
- `JawsAxisPVWrappers` now correctly set a  resolution
- `Velocity_restored` flag now gets autosaved properly
- `SlitGapParameters` only send a setpoint when they are not within tolerance of the setpoint (previously this could lead to twitching)
**Note:** from acceptance criteria for this ticket: 
> Consider writing all logs to central log so it is shown in the server (see put …

Ticket3535 refl ioc logging

---

server_common/channel_access.py

Don't use genie_python channel in tests if possible

Try not to use CaChannel wrapper in test so it runs on redhat

---

Jenkinsfile

Add Microsoft teams connector
See ISISComputingGroup/IBEX#5344
* build messages appear in teams Jenkins channel
---

Add microsoft teams connector

---

ReflectometryServer/ChannelAccess/pv_manager.py
ReflectometryServer/__init__.py
ReflectometryServer/beam_path_calc.py
ReflectometryServer/beamline.py
ReflectometryServer/beamline_constant.py
ReflectometryServer/components.py
ReflectometryServer/config_helper.py
ReflectometryServer/exceptions.py
ReflectometryServer/parameters.py
ReflectometryServer/reflectometry_server.py
ReflectometryServer/test_modules/data_mother.py
ReflectometryServer/test_modules/test_beamline.py
ReflectometryServer/test_modules/test_components.py
ReflectometryServer/test_modules/test_config_helper.py
ReflectometryServer/test_modules/test_engineering_corrections.py

Move config helper from config to inside server. Alter tests to use it
https://github.com/ISISComputingGroup/IBEX/issues/4289
Configs still work and are in the newer style
---

Ticket4289 config for crisp

---

ReflectometryServer/config_helper.py
ReflectometryServer/run_tests.py
ReflectometryServer/test_modules/test_config_helper.py

Add debug code to be run on readhat

Add debug code for rh

---

server_common/helpers.py

If DB is unavailable, log and carry on.

Don't fail if mysql is unavailable

---

DatabaseServer/test_modules/test_database_server.py

* Do `%PYTHON3% run_all_tests.py` on master
* Confirm there are a number of exceptions saying that logging has failed and that the tests take a while waiting for these exceptions
* Run the same tests on this branch and confirm errors do not occur
---

Use a dummy logger during tests

---

server_common/helpers.py

Copied get_macros from refl
https://github.com/ISISComputingGroup/IBEX/issues/5452
-
---

Moves get macros to common

---

server_common/test_modules/test_observable.py

Fix test
- tests run still and run on linux
---

Remove uneeded refernce

---

ReflectometryServer/ChannelAccess/channel_access_constant.py
ReflectometryServer/ChannelAccess/driver_utils.py
ReflectometryServer/ChannelAccess/pv_manager.py
ReflectometryServer/ChannelAccess/reflectometry_driver.py
ReflectometryServer/__init__.py
ReflectometryServer/config_helper.py
ReflectometryServer/file_io.py
ReflectometryServer/ioc_driver.py
ReflectometryServer/parameters.py
ReflectometryServer/test_modules/data_mother.py
ReflectometryServer/test_modules/test_beamline_parameter.py
ReflectometryServer/test_modules/test_config_helper.py
ReflectometryServer/test_modules/test_driver_utils.py
ReflectometryServer/test_modules/test_ioc_driving_layer.py
server_common/observable.py
server_common/test_modules/test_observable.py

Add in beam blocker concept
https://github.com/ISISComputingGroup/IBEX/issues/5456
- An enumerated parameter can be added to a config
- config `add_parameter(EnumParameter("MyName", ["opt1", "opt2"]))`
- A beam blocker can be added to the configuration which allows blades to be driven individually.
- config `s3_params = add_slit_parameters(3, beam_blocker="S") `
- For a CRISP like setup the blade can offset from the beam using the pv_wrapper_for_parameter
```
s3_params = add_slit_parameters(3, 0.00200 * 2, beam_blocker="S")
s3_comp = add_component(Component("s3", PositionAndAngle(0.0, z_s3, 90)))
add_parameter(AxisParameter("S3Offset", s3_comp, ChangeAxis.POSITION, autosave=True), modes=[nr, polarised, laser])
def invert(value, block):
"""
Multiply value by -1 if in South blocker mode, …
```

Ticket5456 beam bloker

---

block_server.py

Always force the CAEN to restart when loading a config.
https://github.com/ISISComputingGroup/IBEX/issues/5590
- The `CAENV895` ioc always restarts when changing a config if it is present in the config.
- Behaviour for other IOCs is unchanged (should not restart if a block is edited for example; should restart if an ioc macro is changed)
- Behaviour when the CAENV895 is not part of the config is unchanged
---

Restart CAEN every time, regardless whether config has changed enough

---

server_common/channel_access.py

remove wait that was introduced to try to make define work
https://github.com/ISISComputingGroup/IBEX/issues/4991
Define works (see tests)
---

Remove wait in set, it isn't needed problem is elsewhere

---

scripts/set_instrument_list.py

Adds INTER to inst list
[#5614](https://github.com/ISISComputingGroup/IBEX/issues/5614)
INTER on inst lists
---

Add INTER to inst list

---

scripts/set_instrument_list.py

Add polref
https://github.com/ISISComputingGroup/IBEX/issues/5629
- polref can be added
---

add polref

---

scripts/set_instrument_list.py

Add SANS2D to inst list

---

scripts/set_instrument_list.py

Create separate INSTLIST PVs for IDAaaS - these are only used by ibex linux client 
---

Group instlists

---

block_server.py
server_common/pv_names.py

Adding heartbeat pv

---

BlockServer/runcontrol/runcontrol_manager.py
BlockServer/test_modules/test_runcontrol_manager.py
block_server.py

https://github.com/ISISComputingGroup/IBEX/issues/5803
https://github.com/ISISComputingGroup/IBEX/issues/5803
https://github.com/ISISComputingGroup/IBEX/issues/5803
---

Ticket5803

---

scripts/set_instrument_list.py

Add groups to inst list

---

server_common/channel_access.py

All ca channel to not get dispp
https://github.com/ISISComputingGroup/IBEX/issues/5931
refl server can use safe_not_quick
---

Add safe not quick

---

server_common/test_modules/test_channel_access.py

Fix test, capuit is called but signature has changed so tests fail
N/A
Tests run
---

Signature of caput changed so update mock

---

ArchiverAccess/archive_data_file_creator.py
ArchiverAccess/archiver_data_source.py
ArchiverAccess/logging_period_providers.py
ArchiverAccess/periodic_data_generator.py
ArchiverAccess/test_modules/__init__.py
ArchiverAccess/test_modules/stubs.py
ArchiverAccess/test_modules/test_archive_configuration.py
ArchiverAccess/test_modules/test_archiver_data_source.py
ArchiverAccess/test_modules/test_periodic_data_generator.py
ArchiverAccess/test_modules/test_time_last_active.py
ArchiverAccess/time_last_active.py
start_archiver_access_cmd.bat
start_archiver_access_cmd.sh

Convert to python 3. Only tricky bits were file, next and StopIteration exception which have equivalents in python3
https://github.com/ISISComputingGroup/IBEX/issues/4880
Tests run, logging in simple IOC can be activated and works
---

Convert to python 3

---

scripts/hex_compress_and_put_pv.py
scripts/instrument_status.py
scripts/set_instrument_list.py

Ticket 4876

---

PULL_REQUEST_TEMPLATE.md

See https://github.com/ISISComputingGroup/IBEX/issues/2185
---

Ticket 2185: Updated pr template

---

RemoteIocServer/test_modules/test_config_monitor.py

Fix remoteioc tests
run   `%PYTHON3% run_all_tests.py` in  `ISIS\inst_servers\master`
* tests pass
---

Fix remoteioc tests

---

scripts/set_instrument_list.py

adding musr to instlist

---

BlockServer/run_tests.py

Make sure all tests are running

---

server_common/ioc_data_source.py

Need a constant for the length of the description field
https://github.com/ISISComputingGroup/IBEX/issues/5899
constant exists
---

Add constant

---

scripts/set_instrument_list.py

See https://github.com/ISISComputingGroup/IBEX/issues/5788
Also, confirm that `CS:INSTLIST` now contains HRPD_SETUP
---

Added HRPD_SETUP to inst list

---

Jenkinsfile

Disable running python2 tests

---

Jenkinsfile

Use python3 for python 3 tests
---

Actually use python3 not python2 for python 3 tests

---

start_collision_avoidance_monitor_cmd.bat

removing commented out py2 reference

---

BlockServer/epics/archiver_manager.py

Retry upload of XML for block archive
See ISISComputingGroup/IBEX#7083
See above ticket
---

retry block xml upload

---

BlockServer/epics/archiver_manager.py

Hide console window created on running archve reload script
See ISISComputingGroup/IBEX#7179
* no popup console window
---

Remove console window on archive reload

---

start_blockserver.bat
start_collision_avoidance_monitor.bat
start_database_server.bat
stop_blockserver.bat
stop_collision_avoidance_monitor.bat
stop_database_server.bat

Update for new cygwin procServ location
See ISISComputingGroup/IBEX#7181
* No flashing window on startup
---

Update for new cygwin location

---

block_server.py

Added a check to see if the configuration we are trying to save is the active one. If the configuration is active we need to reload it so the changes can propagate correctly.
https://github.com/ISISComputingGroup/IBEX/issues/7224
See ticket.
---

Ticket7224

---

block_server.py

Explicitly re set autorestart

---

scripts/set_instrument_list.py

Add WISH setup machine to list of instruments
WISH_SETUP appears in INSTLIST PV
---

Added WISH_SETUP to list of instruments

---

block_server.py

https://github.com/ISISComputingGroup/IBEX/issues/7585

Fix CAEN V895 test

---

DatabaseServer/database_server.py
DatabaseServer/moxa_data.py
DatabaseServer/test_modules/test_database_server.py
schema/blocks.xsd
server_common/pv_names.py

Ticket7720 moxa mappings

---

scripts/set_instrument_list.py

Add OFFSPEC to inst list

---

Jenkinsfile

Add missing always block

---

Jenkinsfile
parse_rules

Change parse rules and disable unstableOnWarning

---

ConfigVersionControl/git_version_control.py
block_server.py

Updated the version control in blockserver to handle multiple repositories.
Added inst scripts to version control
https://github.com/ISISComputingGroup/IBEX/issues/7910
---

Ticket7910 Add inst scripts to version control

---

BlockServer/config/block.py
BlockServer/config/xml_converter.py
BlockServer/core/constants.py
BlockServer/test_modules/test_configuration_xml.py
Jenkinsfile
block_server.py
schema/blocks.xsd

Added the ability to set a block to a value upon config change.
[*Which ticket does this PR fix?*](https://github.com/ISISComputingGroup/IBEX/issues/7642)
---

Ticket7642 set blocks on config change

---

scripts/restore_motor_positions.py

make host required for motor restore script

---

ArchiverAccess/test_modules/__init__.py
BlockServer/test_modules/__init__.py
BlockServerToKafka/test_modules/__init__.py
ConfigVersionControl/test_modules/__init__.py
DatabaseServer/database_server.py
DatabaseServer/exp_data.py
DatabaseServer/ioc_options.py
DatabaseServer/options_holder.py
DatabaseServer/test_modules/__init__.py
DatabaseServer/test_modules/test_options_holder.py
RemoteIocServer/config_monitor.py
RemoteIocServer/gateway.py
RemoteIocServer/remote_ioc_server.py
RemoteIocServer/test_modules/__init__.py
run_all_tests.py
server_common/autosave.py
server_common/ioc_data.py
server_common/ioc_data_source.py
server_common/mocks/mock_ioc_data_source.py
server_common/test_modules/test_channel_access.py
server_common/utilities.py

Remove all references to Six
[Ticket](https://github.com/ISISComputingGroup/IBEX/issues/8297)
---

Remove all references to Six

---

scripts/restore_motor_positions.py

make restore positions script less bad

---

start_blockserver_cmd.bat
start_database_server_cmd.bat

Check for python so if it is missing we can give a sensible error message

Check for python executable

---

scripts/set_instrument_list.py

remove chipir seci=True in instlist

---

start_blockserver.bat
start_database_server.bat

Disable pcon for better log file behaviour
https://github.com/ISISComputingGroup/IBEX/issues/8593
---

Set disable_pcon

---

start_blockserver.bat
start_bs_to_kafka_cmd.bat
start_database_server.bat
stop_blockserver.bat
stop_database_server.bat

Add timestamps

---

scripts/set_instrument_list.py

Add EMMA and MUX to inst list

---

.github/workflows/lint-and-test.yml

the normal workflow needs on.workflow scope - see https://github.com/ISISComputingGroup/EPICS-inst_servers/actions/runs/13800858929/workflow

fix nightly build

---

scripts/set_instrument_list.py

INES now falls under Engineering and Imaging.

INES -> Engineering

---

block_server.py

https://github.com/isiscomputinggroup/ibex/issues/8597
---

Unbreak server_common on py312

---

.github/workflows/lint-and-test.yml
BlockServer/devices/devices_manager.py
BlockServer/fileIO/schema_checker.py
BlockServer/test_modules/test_devices_manager.py
BlockServer/test_modules/test_schema_checker.py
BlockServer/test_modules/test_synoptic_manager.py
constraints.txt

h (fix build)

---

scripts/set_instrument_list.py

Move Mux to be part of muons TS
Motivated by web dashboard wall display.

Update set_instrument_list.py - move MuX

---

start_bs_to_kafka_cmd.bat

Update kafka port

---

start_bs_to_kafka_cmd.bat

Correct IOC name
