BlockServer/block_server.py, BlockServer/epics/gateway.py
The generated gwblock.pvlist used wildcards and so could match
name queries from other instrumemnts that got forwarded on.
This was not a real problem when the block gateway was purely
on localhost network, but as it can now resolve off instrumement
e.g. for beam currrent it needs to be much more selective
=> Change generated gwblocks.pvlist file to be more selective

BlockServer/core/config_list_manager.py
If a component failed to load because it was invalid then it won't appear in the list of subconfig metas. When a configuration using this component is saved the BlockServer throws an uncaught error
<BOOM!>
=> Save config crashes if a component was not loaded

BlockServer/block_server.py
To test:
* Point the remote of your configurations repository to a bad link
* Start the blockserver, confirm that a warning message is logged but otherwise the BlockServer functions normally
=> Ticket951 Git Failure No Longer Crashes Blockserver

BlockServer/core/runcontrol.py
After updating the block server check that setting run control enabled/disabled on blocks works correctly, for old and newly created configuratinos, and the unit tests pass.
=> Changed 1 and 0 to True and False for clarity

BlockServer/block_server.py, BlockServer/blockserver_docs/configuration_rules.rst, BlockServer/core/active_config_holder.py, BlockServer/core/config_holder.py, BlockServer/core/ioc_control.py, BlockServer/epics/procserv_utils.py, BlockServer/mocks/mock_procserv_utils.py, BlockServer/test_modules/ioc_control_tests.py
To test:
From the GUI create a new config with an IOC (TPG300_01 is a good choice) set to auto-start and auto-restart. Save it as "restart"
Edit it and uncheck auto-restart and save as "norestart"
From the command line, start a monitor: 
camonitor %MYPVPREFIX%CS:PS:TPG300_01:AUTORESTART
Open another command line and connect to the TPG300_01 console:
console -M localhost TPG300_01
Load the "restart" configuration. The monitor should report AUTORESTART as On. The IOC should be running and if you stop it, it restarts.
Load the "norestart" configuration. The monitor should report AUTORESTART as Off. The IOC should be running and if you stop it, it DOES NOT restart.
=> Ticket 998: Auto-restart should now work

BlockServer/block_server.py, BlockServer/config/configuration.py, BlockServer/config/xml_converter.py, BlockServer/core/config_holder.py, BlockServer/core/config_list_manager.py, BlockServer/mocks/mock_block_server.py, BlockServer/test_modules/config_holder_tests.py, BlockServer/test_modules/config_list_manager_tests.py
To test this:
* Create a component and add one or more IOCs. Check the xml for the component is saved with the IOCs.
* Add this component to a configuration. Make sure that configuration does not have the IOCs that are contained in the component.
* Check the configuration does not save the component IOCs.
* Check adding Macros, PV Values or PV Sets saves them to the configuration or component, depending on where the change occurs.
As part of this ticket an issue with capitalisation of component names was fixed. To test this:
* Check capitalisation is obeyed when adding a component and reloading a configuration.
* Check configurations with components behave as expected when adding and deleting.
* Check that `caget %MYPVPREFIX%CS:BLOCKSERVER:COMPONENT_NAME:DEPENDENCIES` behaves correctly …
=> Ticket1026 IOCs for components

start_blockserver_cmd.sh
The location of the synoptic.xsd schema file was changed in https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/32.
This PR updates the startup shell script to mirror the changes made to the startup batch file.
=> Updated Linux startup script for new synoptic schema location

BlockServer/block_server.py
Currently they exist as a "read" and are also updated as a monitor. This causes a "NoneType" error to occasionally appear when the config is changed.
=> Blocknames and current_config_details are available as monitors only

DatabaseServer/database_server.py, DatabaseServer/ioc_data.py
A new DB info type of PVCATEGORY will now be used to determine
sample and beamline parameters
See ISISComputingGroup/IBEX#1133   and ISISComputingGroup/EPICS-ioc#21
=> Use PVCATEGORY for sample and beamline parameters

BlockServer/block_server.py, BlockServer/core/devices_manager.py, BlockServer/core/pv_names.py
Verify that the schema of devices screens is made available in the PV %MYPVPREFIX%CS:BLOCKSERVER:SCREENS_SCHEMA (it's a waveform compressed an hexed):
`caget -t -S %MYPVPREFIX%CS:BLOCKSERVER:SCREENS_SCHEMA|uzhex`
Compare with the contents of `schema\screens.xsd`
=> Ticket 1122: Blockserver makes screens schema available as PV

BlockServer/block_server.py, BlockServer/core/config_list_manager.py, BlockServer/core/pv_names.py, BlockServer/test_modules/config_holder_tests.py, BlockServer/test_modules/config_list_manager_tests.py, BlockServer/test_modules/file_path_manager_tests.py
Fixes https://github.com/ISISComputingGroup/IBEX/issues/1280
To test:
* Run the blockserver, confirm that the PV has disappeared and that everything else is functioning as expected
*Run the blockserver unit tests, confirm that they all pass
=> Remove curr changed pv

BlockServer/epics/archiver_manager.py
Relates to https://github.com/ISISComputingGroup/IBEX/issues/1370
To test:
With this branch checked out start your instrument (otherwise restart the blockserver from a console in order to pick up the code change)
Generate/edit a config so that there are some blocks which are logged, and some which aren't.
Go to the page http://localhost:4813/groups
There should be two entries, one for BLOCKS, one for DATAWEB
If you look at the BLOCKS page then the logged blocks should be shown
If you look at the DATAWEB page then the un-logged blocks should be shown
If the pages don't display all the expected groups or blocks, go to http://localhost:4813/restart, then go back to the groups, BLOCKS or DATAWEB pages and the information should be visible.
=> Add a dataweb group of non-logged blocks

BlockServer/epics/archiver_manager.py, BlockServer/epics/archiver_wrapper.py
Fix race condition with archiver restart and mysql config update. Popen is asynchronous, need to wait() for archive details to upload
To test:
prior to merge, swap between two configurations with different named blocks and examine  
http://localhost:4813/group?name=BLOCKS - you should find that occasionally this is not updated and shows old disconnected block names instead.
After merging, this should then work properly every time.
see ISISComputingGroup/IBEX#1413
=> Wait after Popen call

BlockServer/test_modules/config_list_manager_tests.py, BlockServer/test_modules/synoptic_manager_tests.py, server_common/test_modules/utilities_tests.py, server_common/utilities.py
ISISComputingGroup/IBEX/issues/1394
Config names are now truncated to six characters (to accommodate a 60 char PV limit). If the shortened name already exists, the PV is further shortened to four characters, with two numbers being appended for  uniqueness (01, 02, etc.).
=> Ticket1394 truncate long config names 

BlockServer/core/active_config_holder.py, BlockServer/core/pv_names.py, BlockServer/mocks/mock_file_manager.py, BlockServer/test_modules/active_config_holder_tests.py, BlockServer/test_modules/configuration_tests.py, block_server.py, scripts/hex_compress_and_put_pv.py
For ticket ISISComputingGroup/IBEX#1209
The Blockserver now has a new PV (RELOAD_CURRENT_CONFIG) that, when written to, reloads the current configuration.
This means that any IOC that is marked as BOTH auto-start and auto-restart will restart when the current configuration is reloaded.
Also updated unit tests
To test: have one or more IOCs marked as both auto-start and auto-restart as part of your current config, then write any value to the new PV and verify that the IOCs restart.
To write to the PV you can use `scripts/hex_compress_and_put_pv.py` (you might have to copy it one folder up to get it to run)
=> Ticket1209 reload current config

DatabaseServer/test_modules/sqlite_wrapper_tests.py
The EPICS builds are currently failing owing to this change:
https://github.com/ISISComputingGroup/EPICS/commit/1de630b2cca9e0078148f17d2019547665e2ef82
The referenced method was commented out. I've searched EPICS and this is the only place it's used. I've moved the method here and added the new fields added at the referenced change
=> Method only used here. Move from build_ioc_startups and add new fields

DatabaseServer/database_server.py
There were no unit tests, this has broken nothing. To test it, either make sure if you are getting a sockets error that you don't anymore, or make sure you can access an INTERSTING_PVS:IOC:HIGH of some variaty (these are blockserver/database server VIs to allow for the first part to be built), it is likely that the PV exists, but it shouldn't have much info in it.
=> Comment the line

DatabaseServer/test_modules/database_server_test_mysql.py
These tests reference a method and PV that no longer exist. Remove them. I've double-checked and the PV no longer exists anywhere else in EPICS
=> Ticket1515 remove tests that reference removed pv

DatabaseServer/mysql_abstraction_layer.py
Without adding debug comments this is a hard one to locate and test, however, if you have your system running as standard (prior to checking out this branch), open a console to the DBSVR, in another command prompt run the following:
```
camonitor NDW1032:KVLB23:PARS:SAMPLE:HEIGHT NDW1032:KVLB23:PARS:SAMPLE:HEIGHT:SP
```
and run the following in genie_python:
```
for i in range(250):
change_sample_par("HEIGHT",i)
```
there should be some errors, or hangs, or some other odd behaviour visible either in the genie_python script, or in the monitors. Keep restarting the DBSVR (Ctrl-X in the DBSVR console window) until the script completes.
Checkout the branch for this pull request, and restart the DBSVR once more (to load the altered code). Re-run the script and this time it should go through …
=> Lock the SQL interactions to a single thread

DatabaseServer/mysql_abstraction_layer.py
This is a side-effect of the full fix of ticket https://github.com/ISISComputingGroup/IBEX/issues/1516 where we stopped opening a new connection for every query. The change in part makes the connection appear "stale", that is, when queries are run regularly they return the same result in spite of the content of the underlying database having changed.
The solution is to perform a commit after each query, even if the query itself doesn't explicitly update the database. This solves the problem with interesting PVs, as well as a number of other issues like the IOC status not updating properly in the IOC control panel.
=> Auto-commit queries to avoid unwanted caching

BlockServer/runcontrol/runcontrol_manager.py
Do not re-apply previous autorestart value for run control, which should ensure it is always on
See ISISComputingGroup/IBEX#1711
Check run control restart on config/block change
---
=> Do not reappy autorestart on restart

BlockServer/devices/devices_manager.py, BlockServer/fileIO/config_file_event_handler.py, BlockServer/fileIO/schema_checker.py, BlockServer/fileIO/synoptic_file_event_handler.py, block_server.py
_Wait for https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/80 to be merged_
The filewatcher is supposed to be disabled when the block server writes to the file system. However in the previous setup, the asynchronous nature of the write queue meant that often (e.g. synoptics), the filewatcher was re-enabled before the command was executed.
I've changed the flow of logic so that the filewatcher is disabled as part of the execution of the write queue so it will automatically apply to all write commands.
Note that if a write command is executed outside of the queue, as is currently the case for config methods, then they will now throw the error currently reported by the synoptics. This will be fixed by ticket #1500. Please wait for that to be merged first.
Also tidied up some of …
=> Ticket1518 file watcher error

BlockServer/devices/devices_manager.py, BlockServer/test_modules/devices_manager_tests.py
Added a fix for setting device screens (data was not being updated previously).
https://github.com/ISISComputingGroup/IBEX/issues/1724
* Adding, editing and deleting device screens works properly.
---
=> added fix and test for setting device screens

BlockServer/runcontrol/runcontrol_manager.py, block_server.py
BLOCKSVR uses incorrect name for IOCS PV from database server
See ISISComputingGroup/IBEX#1774
Check no IOCS: pv error in blockserver startup
As above
---
=> Fix prefix for IOCS PV from database server

block_server.py
Do a save to file operation as part of setting the current config. This is necessary because IOCs in particular use the file values of macros on startup. Any changes to the current config need to be saved to disc before restarting them.
https://github.com/ISISComputingGroup/IBEX/issues/1595
1. Set up some IOCs
2. Start them and check their macro values
3. Edit the current configuration from the GUI, changing the macro values
4. Wait for the update to complete and check the new macro values
5. Verify that the new values have been used
---
=> Ticket1595 macro updates too slow

.gitignore, BlockServer/core/ioc_control.py, BlockServer/epics/procserv_utils.py, BlockServer/mocks/mock_ioc_control.py, BlockServer/mocks/mock_procserv_utils.py, BlockServer/runcontrol/runcontrol_manager.py, BlockServer/test_modules/ioc_control_tests.py, BlocksCache/blocks_cache.py, DatabaseServer/database_server.py, block_server.py, server_common/utilities.py
The call to restart an IOC returns immediately. When we check waitfor_running, we may query the IOC before it's actually stopped as part of that restart. To avoid this situation, we check the read back on the restart IOC PV to see if there are any operations pending.
In the course of the investigation, I've also added a bit more error handling code.
https://github.com/ISISComputingGroup/IBEX/issues/1770
---
=> Ticket1770 block server restart crash

BlockServer/core/ioc_control.py, BlockServer/mocks/mock_ioc_control.py, BlockServer/runcontrol/runcontrol_manager.py, BlockServer/test_modules/ioc_control_tests.py, block_server.py
I've replaced all of the start-wait and restart-wait loops for IOCS with an equivalent start/restart loop and wait loop. This means that we're not forced to serially wait for each independent IOC to start/restart before moving on to the next one.
https://github.com/ISISComputingGroup/IBEX/issues/1793
---
=> Send start/restart commands for all IOCs before reapplying auto restarts

DatabaseServer/exp_data.py
Alteration to the SQL for experiment team lookups to ensure that multiple experiments do not lead to duplicated team members
Set an RB Number (via the GUI) to one with multiple parts listed, ensure that each name is only listed once, including the surname list (Dashboard) - note that surnames can be repeated but only if there are two Smiths - a Jane and a John, but if only Jane is in the list for the experiment then only one Smith should appear
---
=> Ensure that user entries are only referenced once

BlockServer/core/config_list_manager.py, BlockServer/test_modules/config_list_manager_tests.py
There was a faulty check in the Blockserver that would lead to the dependencies of a component to be overwritten rather than appended, which could lead to the PV holding the components dependencies to be wrongly blank:
1. Comp added to Conf_1 -> dependencies are [Conf_1]
2. Comp added to Conf_2 -> dependencies are [Conf_2], should be [Conf_1, Conf_2]
3. Comp deleted from Conf_2 -> dependencies are [ ], should be [Conf_1]
This change fixes this behaviour.
https://github.com/ISISComputingGroup/IBEX/issues/2007
Can never delete a component that is part of a configuration.
---
=> Ticket2007 delete component dependency check

BlockServer/core/config_list_manager.py
Now propagates changes to Blockserver PV  `ALL_COMPONENT_DETAILS` to its monitors as intended
For https://github.com/ISISComputingGroup/IBEX/issues/1884
Changes made to a component (e.g. to resolve duplicates) take effect immediately and not just after restarting the GUI.
---
=> Keep Component observers updated

DatabaseServer/database_server.py
As a result of this ticket, the length of the IOCs macro was too long. This wasn't reported in the system. I've increased the size of the PV and tidied up the code to better respond to this case in the future
https://github.com/ISISComputingGroup/IBEX/issues/2290
- With all the PRs for this ticket, check that the IOC list still appears in the GUI
- In `C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\DatabaseServer\database_server.py`, decrease PV_SIZE. Make sure that the system responds accordingly (check logs and IOC functionality as above).
---
=> Ticket2290: Log if an encoded value is too long

BlockServer/config/xml_converter.py, BlockServer/core/config_holder.py, schema/groups.xsd
I've taken out much of the logic prohibiting empty groups. Groups will still be discarded if they are empty and have no component. However, empty component groups are permitted in that they indicate the desired ordering for the configuration.
https://github.com/ISISComputingGroup/IBEX/issues/2273
See https://github.com/ISISComputingGroup/ibex_gui/pull/509
---
=> Ticket2273 groups should be orderable

BlockServer/epics/procserv_utils.py
Changed IOCS procServ commands to wait for completion
See ISISComputingGroup/IBEX#1710
Check that IOCs manually start and stop correctly
Check configuration setting for start/stop/autostart etc. all work OK on change of config
Check runControl IOC starts and restarts correctly
=> Wait for IOC start reply from procServ

BlockServer/mocks/mock_channel_access.py, BlockServer/runcontrol/runcontrol_manager.py, BlockServer/test_modules/runcontrol_manager_tests.py
This converts the run control manager to use python `datetime` objects instead of comparing strings.
I've also tidied up the code and added some tests to check what's happening. 
- Run the run control manager tests in the `inst_servers`
- Code review
- Try to reproduce the issue outlined in the ticket description.
This PR is for https://github.com/ISISComputingGroup/IBEX/issues/2526
- Tests pass
- Code does not wait for ~4 minutes
---
=> Fix blockserver config update is slow

server_common/ioc_data.py, server_common/test_modules/test_mysql_wrapper.py
Use select distinct to avoid returning two rows with exactly the same data when querying the database.
https://github.com/ISISComputingGroup/IBEX/issues/2565
Checkout the branch, restart DBSVR.
---
=> Only select distinct fields

BlockServer/devices/devices_file_io.py, BlockServer/devices/devices_manager.py
Fixes a bug introduced with https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/139 where the blockserver would not create and default back to a blank set of device screens if no device screens file was found on the instrument.
The blockserver handles a missing device screens file sensibly.
---
=> If devices file does not exist, create & use blank one

block_server.py
The pevious implementation re-created all existing PV by overwriting
the dictionary entries, the PVs would then get destroyed in C++ when
python garbage collected leading to random crashes.
See ISISComputingGroup/IBEX#2824
* blockserver restarts with many synoptics and clients present
---
=> Only recreate single new PV and not recreate all existing PVs too

BlockServer/synoptic/synoptic_manager.py
`(recommended)` is no longer appended to the default synoptic name. It is superfluous since the default-ness is sent separately. The GUI handles any manipulation of the data owing to its needs.
https://github.com/ISISComputingGroup/IBEX/issues/2527
See GUI PR
---
=> Don't add 'recommended' suffix to synoptic name. Let GUI handle it

BlockServer/core/active_config_holder.py, BlockServer/test_modules/active_config_holder_tests.py, block_server.py
IOCs removed from the active configuration are stopped upon saving the changes.
https://github.com/ISISComputingGroup/IBEX/issues/2447
Removing IOCs from the active configuration stops them.
---
=> Stops IOCs when removed from the current configuration

ArchiverAccess/test_modules/test_log_file_creator.py, BlockServer/test_modules/test_active_config_holder.py, DatabaseServer/test_modules/test_database_server.py, server_common/constants.py
- Fixed a few typos and removed unused imports
- Skipped tests that fail on Linux. These tests are integration rather than unit tests and rely on file system access and platform-specific paths that don't work on Linux. In the long-run, we should fix these but my primary concern at the moment is getting the build working. These are tests that have never been run previously on Linux so these are not new failures
https://github.com/ISISComputingGroup/IBEX/issues/2891
---
=> Ticket2891 fix linux build

ConfigVersionControl/git_version_control.py
Changed the logging level of the version control "Nothing to commit" message to DEBUG, as it is being printed every 5 minutes and can bury more important information.
https://github.com/ISISComputingGroup/IBEX/issues/2980
Logging level of message is now DEBUG
---
=> Changed logging level of "nothing to commit" message to DEBUG

ReflectometryServer/beamline.py, ReflectometryServer/parameters.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_actual_positions.py, ReflectometryServer/test_modules/test_beamline_parameter.py
Individual moves now do not apply any other changed setpoints, but simply reset the latest setpoint readback value for following beamline parameters in the mode.
To achieve this, I have split `update_beamline_parameters` into two methods: 
- one that gets called after an individual move and resets the sp_rbvs of subsequent parameters in the mode
- one that gets called on a beamline move and updates all parameters to their latest values
https://github.com/ISISComputingGroup/IBEX/issues/3551
- Triggering an individual move on a parameter...
- Other functionality is unchanged.
---
=> Ticket3551 refl fix individual move

scripts/set_instrument_list.py
Accidently refactor pvPrefix to be pv_prefix in the dictionary. This correct that.
=> Set instrument prefix back to being correct value

scripts/set_instrument_list.py
See https://github.com/ISISComputingGroup/IBEX/issues/2669
Note that I haven't pushed this to the central PV yet. The reviewer can do this if it passes review.
* Change the 'CS:INSTLIST' to something local
* Run the script
* Confirm that the PV is updated with a dictionary containing the scheduled boolean
Docs have been updated at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Making-an-Instrument-Available-from-the-GUI
---
=> Ticket 2669: Added a flag for if instruments are scheduled

BlockServer/epics/procserv_utils.py, server_common/channel_access.py, server_common/utilities.py
Retry on failure to get valid value from `AUTOSTART` pv.
https://github.com/ISISComputingGroup/IBEX/issues/3335
---
=> Retry on failure to get valid autorestart setting

ReflectometryServer/ChannelAccess/pv_manager.py, ReflectometryServer/ChannelAccess/reflectometry_driver.py, ReflectometryServer/beamline.py
Add alarm property to status PV for alarm view.
Make PV actually go into alarm
https://github.com/ISISComputingGroup/IBEX/issues/3578
1. Alarm appears in alarms view in GUI
1. On load on bad config alarm is MAJOR
---
=> Add alarm state

ReflectometryServer/beam_path_calc.py, ReflectometryServer/beamline.py, ReflectometryServer/parameters.py, ReflectometryServer/test_modules/test_beamline.py, ReflectometryServer/test_modules/test_beamline_parameter.py, ReflectometryServer/test_modules/test_components.py
1. a move triggered on a beamline parameter causes the motors to move
1. Theta readback is correct if super-mirror is before it
https://github.com/ISISComputingGroup/IBEX/issues/3893
1. Set a parameter make sure move sets that parameter and moves the motors to it (readback should update)
1. Set a parameter in a mode make sure all parameters after this are set to set point not changed values
1. With a super mirror in check that that readback is theta at various super mirror angles.
Good setup:
```
from ReflectometryServer.components import *
from ReflectometryServer.geometry import *
from ReflectometryServer.beamline import Beamline, BeamlineMode
from ReflectometryServer.parameters import *
from ReflectometryServer.ioc_driver import *
from ReflectometryServer.motor_pv_wrapper import *
from …
```
=> Update so moves after indiviual move

ReflectometryServer/ioc_driver.py, ReflectometryServer/parameters.py, ReflectometryServer/pv_wrapper.py, ReflectometryServer/reflectometry_server.py, ReflectometryServer/test_modules/test_beamline.py, ReflectometryServer/test_modules/test_beamline_parameter.py, ReflectometryServer/test_modules/test_components.py, ReflectometryServer/test_modules/test_ioc_driving_layer.py, server_common/channel_access.py
Remove genie_python as a global import to avoid test failures if genie_python is not installed. It is only needed when accessing actual pvs,
=> Make independent of genie_python and CaChannel

ReflectometryServer/ChannelAccess/pv_manager.py, ReflectometryServer/ChannelAccess/reflectometry_driver.py, ReflectometryServer/beam_path_calc.py, ReflectometryServer/beamline.py, ReflectometryServer/components.py, ReflectometryServer/example_beamline.py, ReflectometryServer/ioc_driver.py, ReflectometryServer/movement_strategy.py, ReflectometryServer/parameters.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_actual_positions.py, ReflectometryServer/test_modules/test_beamline.py, ReflectometryServer/test_modules/test_beamline_parameter.py, ReflectometryServer/test_modules/test_components.py, ReflectometryServer/test_modules/test_config/error_config/refl/config.py, ReflectometryServer/test_modules/test_config/good_config/refl/config.py, ReflectometryServer/test_modules/test_ioc_driving_layer.py
Disable beam calculation for certain modes
https://github.com/ISISComputingGroup/IBEX/issues/3890
When a disable mode is introduced the components act as if they were no longer linked. Changing the value is changing with reference to where it was. E.g. change theta no longer change the following slit height. Changing the slit height is with reference to where it was when it entered disable mode.
---
=> Ticket3890 disable mode

ReflectometryServer/ChannelAccess/reflectometry_driver.py
Fixes a bug where parameters in the reflectometry IOC wrapping a motor would not get updated properly when an underlying PV is written to directly. Currently only relevant for slit gap parameters.
Required for testing:
- Set up a Jawset on a simulated Galil
- Set up a `config.py` configuration file in `<machine>\configurations\refl\` that contains a slit gap parameter pointing at the jaw set. Below is a minimal config that should work. (Talk to me if this gives you any problems)
- Start the `REFL` IOC
```
from ReflectometryServer import *
def get_beamline():
vgap = SlitGapParameter("S1VG", AxisPVWrapper("MOT:JAWS:VGAP"), True, sim=True, init = 0)
mode = BeamlineMode("mode", [])
beam_start = PositionAndAngle(0.0, 0.0, 0.0)
bl = Beamline([], [vgap], [mode], [], beam_start)
return bl
``` …
=> Add listener at driver level

BlockServer/core/active_config_holder.py, BlockServer/core/config_holder.py, BlockServer/epics/procserv_utils.py, BlockServer/test_modules/test_active_config_holder.py, block_server.py
Config is not cached on change so that check if anything changed since last change does not work. Correctly cache config on change. Also remove check on blocks changed always restart block archiver, to be but right with more testing later.
https://github.com/ISISComputingGroup/IBEX/issues/4090
1. Workflow stated works
1. Test when IOC is in a component and not in a component
1. Test on load of config and edit of current config 
1. If macro changed then IOC reloaded
1. If macro not changed IOC not reloaded
1. Code can be applied as a hot fix and details are in ticket #4107 (https://github.com/ISISComputingGroup/IBEX/issues/4107)
---
=> Cache the last config on config change

ReflectometryServer/ChannelAccess/reflectometry_driver.py, ReflectometryServer/beamline.py, ReflectometryServer/ioc_driver.py, ReflectometryServer/pv_wrapper.py, ReflectometryServer/reflectometry_server.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_ioc_driving_layer.py
https://github.com/ISISComputingGroup/IBEX/issues/4046
---
=> Handle disconnected PVs

ReflectometryServer/beamline.py, ReflectometryServer/ioc_driver.py, ReflectometryServer/pv_wrapper.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_ioc_driving_layer.py, server_common/utilities.py
Made changes so that no move instruction is issued to motors that are already in position. This is checked at the IOC driver level by comparing the component (beam path) level setpoint in the reflectometry IOC against the setpoint value of the relevant motor axis. If they are within tolerance (=motor resolution), it does not try to move them.
https://github.com/ISISComputingGroup/IBEX/issues/3539
- System issues move command if component setpoint and motor setpoint are out of step
---
=> Ticket3539 do not move unchanged components

server_common/constants.py, start_bs_to_kafka_cmd.bat
Adds a script to run BlockserverToKafka, see https://github.com/ISISComputingGroup/IBEX/issues/4237
* Ensure you have the library installed in https://github.com/ISISComputingGroup/genie_python/pull/162
* Ensure you have the latest base config from https://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=shortlog;h=refs/heads/master
* Ensure you have https://github.com/ISISComputingGroup/EPICS/pull/167
* Start an instrument
* Confirm BSKAFKA has started and has logged in the normal IOC space
* Confirm that a valid forwarder configuration has been pushed to the forwarder_config topic. (to do this get in touch with @DominicOram, @matthew-d-jones or @rerpha)
* Change configuration and confirm the forwarder_config has appropriately changed
---
=> Ticket 4237: Run BlockserverToKafka as Default

start_bs_to_kafka_cmd.bat
See https://github.com/ISISComputingGroup/IBEX/issues/4347
* Start an instrument/switch config on your dev machine
* Do the same on DEMO
* Run the attached [python code](https://github.com/ISISComputingGroup/EPICS-inst_servers/files/3192114/test_4347.zip) looking at the test server (tenten.isis.cclrc.ac.uk:9092) confirm that there is a message about your local blocks on the server but not about DEMO's
* Run the script against livedata.isis.cclrc.ac.uk:9092, confirm there is data from DEMO but not from your machine
---
=> Ticket 4347: Push dev data to test cluster

ReflectometryServer/ChannelAccess/pv_manager.py, ReflectometryServer/ChannelAccess/reflectometry_driver.py, ReflectometryServer/beamline.py, ReflectometryServer/parameters.py, ReflectometryServer/reflectometry_server.py
This ticket is part of the work to provide the parameters found on the 'Components: Positions relative to beam' screen on the opi in the same order in which they are found in the config. The work also provides an indication as to whether the parameter is in the mode or not. 
[#4264](https://github.com/ISISComputingGroup/IBEX/issues/4264)
---
=> Ticket4264 reflectometry ordered positions

ReflectometryServer/parameters.py
Remove set of set point readback from lower PV in the slit gaps
https://github.com/ISISComputingGroup/IBEX/issues/4307
1. Set the Jaws from the lower OPI, setpoint readback on reflectometry OPI does not change
---
=> Remove update of sp rbv from lower pvs

ReflectometryServer/beam_path_calc.py, ReflectometryServer/components.py, ReflectometryServer/geometry.py, ReflectometryServer/movement_strategy.py, ReflectometryServer/test_modules/test_beamline.py, ReflectometryServer/test_modules/test_beamline_parameter.py, ReflectometryServer/test_modules/test_components.py
Make theta readback work with setpoint.
https://github.com/ISISComputingGroup/IBEX/issues/4306
1. With an offset on the detector, theta readback is the same as theta setpoint.
---
=> Use the setpoint offset when calculating theta

ReflectometryServer/beamline.py, ReflectometryServer/ioc_driver.py, ReflectometryServer/pv_wrapper.py, ReflectometryServer/test_modules/test_ioc_driving_layer.py
Allow axes to not be synchronised, this means the velocity on that axis will not be set on it.
https://github.com/ISISComputingGroup/IBEX/issues/4310
1. A non-synchronised axis does not have its velocity change in a move with other axes
1. Synchronised axis does have its velocity change in a move with other axes if the other zxes will take longer to move
---
=> Allow axes to not be synchornised

ReflectometryServer/pv_wrapper.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_pv_wrapper.py
Cache the latest value for motor velocity in the PVWrapper class. This means the server does not have to make `caget` calls to get the velocity of each individual axis for a synchronized move and improves system performance and stability. 
https://github.com/ISISComputingGroup/IBEX/issues/4603
- The reflectometry IOC performs equal to or better than before
- All unit and IOC tests still pass
---
=> Cache velocity, edit mock class to reflect change

block_server.py
Updated the docstring to reflect the new behaviour changed in https://github.com/ISISComputingGroup/EPICS-inst_servers/commit/fad6941f4e289b10dd722b5bafaa5e0b2f03150e. Added a warning which gets logged if `set_curr_config` is used incorrectly.
https://github.com/ISISComputingGroup/IBEX/issues/4605
---
=> Added log message warning if set_curr_config is used incorrectly

ReflectometryServer/beam_path_calc.py, ReflectometryServer/parameters.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_beamline.py
Fixes a bug where setpoint and readback values after  theta would be initialised incorrectly if the incoming beam at theta was not the straight through beam as the outgoing beam from theta SP was wrong.
https://github.com/ISISComputingGroup/IBEX/issues/4462
Given a supermirror in beam with non-zero angle on IOC startup, a detector with offset and a Theta angled to this detector:
---
=> Ticket4462 init beam path

ReflectometryServer/ChannelAccess/pv_manager.py, ReflectometryServer/ChannelAccess/reflectometry_driver.py, ReflectometryServer/beam_path_calc.py, ReflectometryServer/ioc_driver.py, ReflectometryServer/parameters.py, ReflectometryServer/pv_wrapper.py, ReflectometryServer/test_modules/data_mother.py
Two new PV types:
- `CHANGING`: Is the parameter (and underlying component/s) value changing.
- `RBV:AT_SP`: Has the read back value arrived at target set point.
The `CHANGING` PV can be used to establish if the parameter (and its underlying components) value is changing. And while currently this extends to rotating (for angular components), displacing (for displacement and binary components), it's general enough to extend to other future components that can ramp for example.
The `RBV:AT_SP` PV is used as a confirmation that given some requested change via a target set point, that the read back value matches this within some tolerance. This tolerance is an new available argument when creating the parameter in the configuration file. As a side note the binary `InBeamParameter` parameter …
=> Ticket 4295 - Reflectometry: Propagate moving state

ReflectometryServer/beamline.py, ReflectometryServer/ioc_driver.py, ReflectometryServer/pv_wrapper.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_ioc_driving_layer.py, ReflectometryServer/test_modules/test_pv_wrapper.py
The server now gets the direction and backlash move and speed for each axis and uses them to take backlash into account for move duration calculation. To ensure that motors still move at the intended speed, also modified `perform_move` to subtract the duration of the backlash from the previously calculated duration.
Added errors when motor or backlash speed is 0, as this would cause it to divide by zero.
Updated wiki [Reflectometry Composite Driving Layer](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Composite-Driving-Layer)
https://github.com/ISISComputingGroup/IBEX/issues/4541
Added new tests for the PV wrapper and added new tests for the IOC driver which checks the calculations in a variety of situations.
---
=> Ticket4541 Take backlash into account for move duration

block_server.py
This fixes an issue seen during deployment, where on initial ibex server start the correct set of IOCs were not being started.
I believe this was a logic issue in some code that was specifically only initialising a config - I think there was a race which sometimes meant the ioc was being started and then immediately stopped again.
I have replaced it with a call to a common start_ioc function.
https://github.com/ISISComputingGroup/IBEX/issues/4660
This is difficult to system/unit test - I can't reproduce it on non-instrument machines. I have added a manual system test for it to the usual spreadsheet.
Issue is fixed (can check on MUONFE for example)
---
=> Fix blockserver starting iocs

scripts/set_instrument_list.py
To test, verify you can connect to DETMON using the drop-down list in the GUI.
Note: changing DETMON's prefix to `IN:DETMON:` is probably a better solution but the algorithm to turn machine name into instrument prefix is in lots of places (gui/genie_python/blockserver/config_env) and can't handle the `NDA` prefix. This solution will get something working and then we can look at setting in to something more friendly down the line
=> Fix prefix used for detmon

ReflectometryServer/beam_path_calc.py, ReflectometryServer/beamline.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_beamline.py
Added tests to ensure beamline initialises correctly when motion axes are not perpendicular to the beam. Renamed `_absolute_angle` to the more descriptive `_angle_to_natural_beam`.
https://github.com/ISISComputingGroup/IBEX/issues/3906
- Tests are sensible and pass
- Variable names are sensible
---
=> Ticket3906 comp angle relative to beam

DatabaseServer/options_loader.py, DatabaseServer/test_files/config.xml, schema/iocs.xsd
As title.
https://github.com/ISISComputingGroup/IBEX/issues/2328
https://github.com/ISISComputingGroup/IBEX/issues/4624
---
=> Ticket2328/4624 Database server reads default macro values if they are available

DatabaseServer/database_server.py
Increased pv char waveform size from 64k to 128k. Reqiured for the DETMON blocks database encoding
https://github.com/ISISComputingGroup/IBEX/issues/4182
Flash review only
---
=> Increased pv char waveform size from 64k to 128k

DatabaseServer/database_server.py, DatabaseServer/test_modules/test_database_server.py, server_common/ioc_data_source.py, server_common/mocks/mock_ioc_data_source.py, server_common/pv_names.py, server_common/test_modules/test_ioc_data.py
This pull request has minor changes made to the DB Server so that for an instrument it sets up a PV which contains data about all the Low Interesting PVs of that instrument, read from the MySQL database.
https://github.com/ISISComputingGroup/IBEX/issues/4797
If you go into an epics terminal and type in caget -t -S IN:YOUR_INSTRUMENT:CS:BLOCKSERVER:PVS:INTEREST:LOW | uzhex should return an empty list (or a non empty list with low interesting pvs if your developer machine has low interesting pvs).
---
=> Ticket4797 db server low interest p vs

BlockServer/config/metadata.py, BlockServer/config/xml_converter.py, BlockServer/core/config_holder.py, BlockServer/core/inactive_config_holder.py, schema/meta.xsd
Block server to make changes to the XML file after the configuration is edited or new configuration is changed with a new sub-element.
Ticket: https://github.com/ISISComputingGroup/IBEX/issues/4794
Check if the GUI retains the ticked box after the config is protected even after closing the window
---
=> Changes to blockserver to write new sub element to meta.xml

ReflectometryServer/pv_wrapper.py, ReflectometryServer/test_modules/test_pv_wrapper.py
Changed the `_JawsAxisPVWrapper` to init backlash to `0` (zero) on initialization.
[#4638](https://github.com/ISISComputingGroup/IBEX/issues/4683)
---
=> Ticket 4638 - Set backlash to zero on init for _JawsAxisPVWrapper

ReflectometryServer/parameters.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_beamline_parameter.py
- Changed the method for move component to use the set point read back (rather than set point).
- Created tests for the server to detect if this spurious behavior occurs again.
[#4251](https://github.com/ISISComputingGroup/IBEX/issues/4251)
---
=> Ticket 4251 -  Individual move of theta causes other parameters to move

ReflectometryServer/ioc_driver.py
Updated the `IocDriver` class to have a init value of `None` for the `_out_of_beam_position`. 
Previously if the component was parked out of the beam, and that value was autosaved for the parameter, if the server was started you would see the error described in the ticket. This was because the `DisplacementDriver` class inherited from `IocDriver` and only checks against `is not None` in the `_get_in_beam_status` method.
1. Checkout this branch and the associated IOC system tests branch
1. Run the reflectometry initialisation tests (refl_init) (tests should pass)
1. Remove init value in `IocDriver` for `_out_of_beam_position`
1. Run the reflectometry initialisation tests (refl_init) (tests should fail)
=> Ticket 4899 - Reflectometry: Fix error when DisplcementDriver is created based on a component which is out of the beam

server_common/autosave.py
Floats can not be iterated through so can not have \n checked in them.
error on refl startup
1. Parameter can be autosaved
---
=> Fix bug saving floats

RemoteIocServer/test_modules/test_config_monitor.py, RemoteIocServer/utilities.py
Fix red hat tests (it has no genie_python)
=> Allow unit tests to be run with no genie_python

RemoteIocServer/config_monitor.py, RemoteIocServer/utilities.py, server_common/channel_access.py
Move all genie python access to channel access wrapper. Then make sure it is not used during tests.
=> Move all genie python access to channel access wrapper

BlockServer/config/block.py, BlockServer/config/configuration.py, BlockServer/config/xml_converter.py, BlockServer/core/config_holder.py, BlockServer/core/constants.py, BlockServer/runcontrol/runcontrol_manager.py, BlockServer/test_modules/test_configuration_xml.py, BlockServer/test_modules/test_runcontrol_manager.py, schema/blocks.xsd
Add flag to runcontrol to control behaviour when pv is invalid or disconnected.
https://github.com/ISISComputingGroup/IBEX/issues/4703
- Flag works as expected
---
=> Allow options for disconnected blocks in run control

block_server.py
If the remote pv prefix is not set in the config then it is none during the check for empty
fix system tests which fail because the config has no remote_pv_prefix
A config with an ioc with no remote pv prefix starts on config change
---
=> If there is no remote pv prefix assume it is Empty not set

ReflectometryServer/ChannelAccess/reflectometry_driver.py, server_common/loggers/isis_logger.py, server_common/test_modules/test_log_writer.py
Made ioc log threaded
ISIS Pv Log which gets called on any write in the reflectometry server
https://github.com/ISISComputingGroup/IBEX/issues/3904
1. Successful write to a PV is logged in the put log (`C:\data\<latest>_ICPputlog.txt`)
There are currently no automated tests for this I do not know how to test that a value will get written to the put log. Is that ok because it is diagnostics (added a manual test)
---
=> On successful PV write value is sent to put log

schema/ioc_types.xsd
Changed Macro values to 256 in Schema
[#4934](https://github.com/ISISComputingGroup/IBEX/issues/4934)
---
=> changed max size for macro values to 256 characters

BlockServer/site_specific/default/general_rules.py
GUI allows configuration description to be free text.
https://github.com/ISISComputingGroup/IBEX/issues/5144
Can save and load configs which have special characters in its description
**Note:**
Restart block server to test this
=> Allow free characters in GUI description for configurations edit/create

DatabaseServer/database_server.py
Only updates database PVs when they actually change to reduce client side load.
On master:
* `camonitor %MYPVPREFIX%CS:BLOCKSERVER:IOCS` and confirm it continues to update despite the database not changing
* Use the JVisualVM to monitor the client CPU usage
On this branch:
* Confirm `camonitor %MYPVPREFIX%CS:BLOCKSERVER:IOCS` only gives one update
* Confirm client CPU usage has decreased, see below where the branches were switched a couple of times:
* On the new branch confirm that the dbserver still updates when expected i.e. start an IOC and confirm it shows as started in the start/stop dialog
---
=> Only update PVs when data has changed

ReflectometryServer/beam_path_calc.py, ReflectometryServer/beamline.py, ReflectometryServer/components.py, ReflectometryServer/file_io.py, ReflectometryServer/geometry.py, ReflectometryServer/parameters.py, ReflectometryServer/pv_wrapper.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_beamline.py, ReflectometryServer/test_modules/test_beamline_parameter.py, ReflectometryServer/test_modules/test_components.py, ReflectometryServer/test_modules/test_config/mode_nonexistent.txt, ReflectometryServer/test_modules/test_config/mode_pnr.txt, ReflectometryServer/test_modules/test_config/params.txt, ReflectometryServer/test_modules/test_engineering_corrections.py, server_common/autosave.py, server_common/test_modules/test_autosave.py
Save incoming beams for all componetns on enter disable mode 
Restore on init
https://github.com/ISISComputingGroup/IBEX/issues/3897
See ticket
---
=> Ticket3897 disable mode save

server_common/ioc_data_source.py
Change timestamp to one that will be accepted in the latest version of mysql
https://github.com/ISISComputingGroup/IBEX/issues/4918
---
=> ioc startup fix

server_common/channel_access.py, server_common/test_modules/test_channel_access.py
Ensure number of threads are capped by using a thread pool
https://github.com/ISISComputingGroup/IBEX/issues/5334
Number of threads does not increase over time on multiple puts from, for instance, ca server
---
=> Ticket5334 cap number of threads

schema/blocks.xsd
Changed type of block deadband in xml schema from decimal to double. This allows values of less than 1E-4 to be entered and allows scientific notation to be used.
https://github.com/ISISComputingGroup/IBEX/issues/4958
When the following deadbands are set, the configuration saves and changes of value less than the deadband are not archived in the database (this can be tested by going to http://localhost:4813/group?name=BLOCKS and selecting the block you're setting, then seeing if last archived value updates or not):
* 1E-6
* 0.000001
* 1e6
* 1000000
* 0
---
=> Allow numbers smaller than 1E-4 for block deadband

ReflectometryServer/pv_wrapper.py
There was a bug with redefining a motor position through a reflectometry parameter, where the reflectometry IOC would write 
`MTRXXXX.SET` --> `SET`
`MTRXXXX.SET` --> `USE`
`MTRXXXX.VAL` --> `(new position)`
instead of 
`MTRXXXX.SET` --> `SET`
`MTRXXXX.VAL` --> `(new position)`
`MTRXXXX.SET` --> `USE`
resulting in the motor to move to the given position instead of accepting it as the new current position. This change just ensures the new position is set before leaving the `SET` context.
=> Ensure position is set while still in SET context

ReflectometryServer/reflectometry_server.py
- Moved an import statement so it is executed after its directory has been added to the path. (was crashing the reflectometry server on startup)
- Removed some unused imports
=> Fix reflectometry server imports

ReflectometryServer/__init__.py, ReflectometryServer/parameters.py, ReflectometryServer/test_modules/data_mother.py, ReflectometryServer/test_modules/test_beamline_parameter.py, ReflectometryServer/test_modules/test_set_current_motor_position.py
- Generalised class for parameters that do not require the component layer for beam tracking, but talk directly to motor PVs.
- Fixed a bug where Angle Parameters RBVs on a `TiltingComponent` would not update properly . They should listen for `PhysicalMoveUpdate` rather than `BeamPathUpdate` - just happened to work on most angles as they also triggered a `BeamPathUpdate`)
https://github.com/ISISComputingGroup/IBEX/issues/4967
- SlitGapParameters behaviour is unchanged
- DirectParameters work for any PV Wrapper
- Create a `TiltingComponent` with an `AngleParameter` not linked to anything else (e.g. Theta) - parameter RBV should stay in sync with motor RBV when moved
---
=> Ticket4967 refl opi improvements

ReflectometryServer/test_modules/test_config_helper.py
Try to fix the error on red hat test. This could be caused because the object isn't used outside the context, I can't see why else this might be broken.
=> Try moving use of wrapper in

ReflectometryServer/config_helper.py, ReflectometryServer/test_modules/test_config_helper.py
Fix test don't use Call.args use Call[0]
=> Address arguments correctly and remove prints.

ReflectometryServer/__init__.py, ReflectometryServer/movement_strategy.py
Allow python2 to pass inst_servers by not importing reflectometry in python 2
Fix tests
- tests pass on red hat linux
---
=> Fix rh build

BlockServer/epics/gateway.py, BlockServer/runcontrol/runcontrol_manager.py, BlockServer/test_modules/test_epics_gateway.py
Fixes two issues:
- aliases were not being created for AC and DC, just for RC, so alerts and detector overcount would not work
- the reading of SOI in runcontrol was now pointing at a non exisiting PV and it then disabled run control. I have fixed this, but i am not completely happy with the fix as it is starting to look a bit circular in aliases. I am not sure if I need original or upper cse only in this alias 
---
=> Add initial fix for SOI issue

server_common/channel_access.py
Alarm states must be int enums (like channel access)
Fix tests
Tests run with no genie_python installed.
---
=> Make channel access close enough without genie_python to allow tests to pass

server_common/helpers.py
get_macro_values was erroring because the default value was an empty string which cannot be parsed as json, so just give an empty dictionary. The values are accessed as a dictionary normally.
---
=> Return empty dict if not defined rather than error

server_common/helpers.py
EPICS/iocstartup/ioctesting.cmd is not run with pcaspy IOCs. Define the same macros for them here.
https://github.com/ISISComputingGroup/IBEX/issues/5633
---
=> Push through macros to pcaspy iocs

DatabaseServer/exp_data.py, DatabaseServer/test_modules/test_exp_data.py
Fix g.change_users() not setting users correctly from IBEX
https://github.com/ISISComputingGroup/IBEX/issues/5863
`g.change_users()` changes user correctly from GUI
---
=> change_users() not setting users correctly

RemoteIocServer/config_monitor.py, RemoteIocServer/gateway.py, RemoteIocServer/remote_ioc_server.py, RemoteIocServer/test_modules/__init__.py, RemoteIocServer/test_modules/test_config_monitor.py, start_remote_ioc_server.bat
Converts the remote IOC server to run under python 3. 
Have done the bare minimum for this, it was written with six anyway so didn't really need to change much. 
Run through https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Remote-IOCs and run an IOC on the remote machine, then see if you can access it from the local one running IBEX
__nb: this will likely not work on the VPN, i'm not sure why, i tried it with DEMO and my local machine but it didn't work__
See ticket - ISISComputingGroup/IBEX#5905
---
=> Ticket5905 convert remote ioc server

BlockServer/core/on_the_fly_pv_interface.py, BlockServer/devices/devices_manager.py, BlockServer/runcontrol/runcontrol_manager.py, BlockServer/synoptic/synoptic_manager.py, BlockServer/test_modules/test_devices_manager.py, block_server.py, server_common/utilities.py
Update pv is a string but was treated as a bytes.
N/A
Device screens can be saved
---
=> Correct the byte conversion in device screens

DatabaseServer/database_server.py
This is like #231 but spotted during system tests as now with every IOC being started there are far more PVs being put into the database
* Increase space for storing all PV names list
* system tests DBSVR no longer reports "Too much data to encode PV TE:SPARE70:CS:BLOCKSERVER:PVS:ALL. Current size is 128000 characters but 130990 are required" 
---
=> Increase PV array size

ConfigVersionControl/git_version_control.py, ConfigVersionControl/test_modules/test_version_contol.py
Be more cautious on which branches to push
Run the unit tests, confirm that branches that are not named after your machine are not being pushed
---
=> Only push on branches with the same name as your machine

BlockServer/epics/gateway.py, BlockServer/runcontrol/runcontrol_manager.py, BlockServer/test_modules/test_epics_gateway.py
Add rule to terminate block list searches early if the PV does not have block name syntax.
This includes removing of handling of uppercase versions of run control PVS which are now done vin the IOC itself
See ISISComputingGroup/IBEX#5925
* Block are still looked up OK, testing improved performance may be hard
* run control works as before
---
=> Only search for valid block syntax

BlockServer/fileIO/schema_checker.py, BlockServer/synoptic/synoptic_manager.py, BlockServer/test_modules/test_synoptic_manager.py
Correctly handle bytes and string when passing xml_data around the blockserver synoptic_manager.
- Attempt to reproduce using https://github.com/ISISComputingGroup/IBEX/issues/6162#issue-798487838 and confirm the log contains no bytes error. 
- Run inst_servers tests and confirm no failures
- Confirm handling of bytes and strings in the code is appropriate
https://github.com/ISISComputingGroup/IBEX/issues/6162
---
=> Blockserver synoptics: handle bytes and string correctly

scripts/set_instrument_list.py
changed CRISP to not be Scheduled. is a test instrument so has no data for RB number populator.
https://github.com/ISISComputingGroup/IBEX/issues/6465
CRISP not scheduled on the database populator
---
=> Ticket6465 CRISP should not be scheduled

server_common/loggers/isis_logger.py
On logging failure, print message that was attempted to be logged - this particularly affected caPutLog messages
See ISISComputingGroup/IBEX#6950
---
=> Print message to console on logger connect failure

scripts/set_instrument_list.py
* Fix warning printed saying PV wasn't identical when it was
* remove duplication in code calculating instrument groups 
* Run code before and after change, compare `CS:INSTLIST` PV after each case - it should not change
* The other e.g. `CS:INSTLIST:MUON` will change, but that should just be that `groups[]` is now populated in the JSON. These values are only used on IDAAS, `CS:INSTLIST` above is the only one affecting instruments. 
* Above tests pass, `CS:INSTLIST` being unchanged is the most important
---
=> Fix incorrect warnings printed; remove code duplication

BlockServer/epics/archiver_manager.py
Change to use subprocess.run as current implementation hangs
if too much output. Currently we do not throw an exception which
is the same behaviour as the original code
Run up instrument, on startup/change of config you should now see output from  running `set_block_config.bat` that looks a biy like
```
INFO: b'\r\nC:\\Instrument\\Apps\\EPICS-DEBUG2\\ISIS\\inst_servers\\master>set STARTARCHIVEDIR=C:\\Instrument\\Apps\\EPICS-DEBUG2\\CSS\\master\\ArchiveEngine\\ \r\n\r\nC:\\Instrument\\Apps\\EPICS-DEBUG2\\ISIS\\inst_servers\\master>set ARCT_EXE=C:\\Instrument\\Apps\\EPICS-DEBUG2\\CSS\\master\\ArchiveEngine\\..\\css-win.x86_64\\css_archive_config_tool\\ArchiveConfigTool.exe \r\n\r\nC:\\Instrument\\Apps\\EPICS-DEBUG2\\ISIS\\inst_servers\\master>if not exist …
```
=> Use subprocess.run to avoid output hang issue

BlockServer/core/active_config_holder.py, BlockServer/mocks/mock_procserv_utils.py, BlockServer/test_modules/test_active_config_holder.py, block_server.py
Ensure the blockserver only restarts IOCS which have actually changed.
https://github.com/IsisComputingGroup/ibex/issues/7135
Also fixes https://github.com/ISISComputingGroup/IBEX/issues/5572
- Blockserver only restarts IOCs which have changed, even if switching between configs that have different IOCS.
* Changed means that any of macros/sim level/autorestart/pv values etc have changed, for this particular IOC
- Unit tests in this repo pass
- System tests (see separate PR) also pass
---
=> Prevent restarting IOCs that don't need restarting

BlockServer/test_modules/test_active_config_holder.py
Hide some exceptions from the log file by mocking an additional method.
These exceptions didn't actually cause test failures, but did cause a spurious `TypeError: encoding without a string argument` to be printed during some tests if ibex server wasn't running in the background.
=> Hide exceptions by mocking get_iocs

BlockServer/site_specific/default/block_rules.py, BlockServer/site_specific/default/general_rules.py
Updated block name regex to **limit block name** entry in the GUI to ~~20~~ **25 characters**.
Updated error message to include correct name length.
https://github.com/ISISComputingGroup/IBEX/issues/3647
See manual test **20:27, #3647** 
- Find out what the limit is for this and place a restriction in the GUI configuration.
- Write a test which checks that the run control works for long PV names.
- Check all current configurations for block names that are too long.
Character limit justification: 
~~22 was found to be the actual limit (by checking run control log for different lengths), but to be completely safe, have enforced 20.~~
Using https://github.com/ISISComputingGroup/EPICS-RunControl/pull/14, limit is now 29 as mentioned in comments on ticket, 
**have enforced a limit of 25** for …
=> Updated name regex & error message

CollisionAvoidanceMonitor/move.py
Fix for new location of `Sequence` in python 3.10
=> Fix CAM unit tests

BlockServer/site_specific/default/block_rules.py, BlockServer/site_specific/default/general_rules.py
Refactored edit from this [PR](https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/368) from [Ticket #3647](https://github.com/ISISComputingGroup/IBEX/issues/3647). 
Reverted `REGEX_ERROR_TEMPLATE_PV_NAME` message and specified name length limit in `block_rules.py` locally (as it was being used for group name validation also).
=> Fix regex error message to have char limit for blocks only

BlockServer/test_modules/test_component_switcher.py
Updated `.called-with` with `.assert_called_with` and corrected incorrect function name
run `dev_build_python.bat` and then check that the test passes
=> Fix for failing release test

schema/blocks.xsd
Change schema so exponential notation is allowed - though this had already been merged from somewhere? It is currently used on LET 
Already in use on LET
See ISISComputingGroup/IBEX#7823
=> Make rc limits double not decimal for exponential format

scripts/set_instrument_list.py
Modified the dictionary to show if instrument uses SECI or not and any functions that may use this value. 
Also added the instruments to the list that use SECI but have not been included. Gathered from this page: http://beamlog.nd.rl.ac.uk/inst_summary.xml.
[Link to ticket](https://github.com/ISISComputingGroup/IBEX/issues/8001)
---
=> Ticket8001 futher imporvements to deploy script

DatabaseServer/database_server.py, DatabaseServer/moxa_data.py, server_common/snmpWalker.py
Added a new file to perform SNMP walk and construct the result in a map of user-readable key-value pair.
Modified Moxa data build logic to include MIB level SNMP data. Code doesn't impact the structure of the response that it finally sends to the IBEX GUI.
https://github.com/ISISComputingGroup/IBEX/issues/8109
The python module should compile, and all tests should pass.
---
=> Added a SNMP walker. Added logic to invoke it while building Moxa data

DatabaseServer/moxa_data.py
when a hostname lookup fails (or if a bad IP is given ie `1.1.1.1.` - notice the trailing period) t would be nice to print it out for debugging purposes as it means if you accidentally type the wrong ip in nport driver manager then apply and close it you then need to re-open nport driver manager to see your mistake
---
=> print out when hostname lookup fails

DatabaseServer/database_server.py, DatabaseServer/exp_data.py, DatabaseServer/ioc_options.py, DatabaseServer/mocks/mock_exp_data.py, DatabaseServer/mocks/mock_procserv_utils.py, DatabaseServer/moxa_data.py, DatabaseServer/options_holder.py, DatabaseServer/options_loader.py, DatabaseServer/procserv_utils.py, DatabaseServer/test_modules/__init__.py, DatabaseServer/test_modules/test_exp_data.py
Performed ruff and pyright checks on the database server
[*Which ticket does this PR fix?*](https://github.com/ISISComputingGroup/IBEX/issues/8527)
https://github.com/ISISComputingGroup/genie_python/pull/442
=> Pyright and ruff checking for Database Server

scripts/set_instrument_list.py
Add HIFI/ARGUS as IBEX to the instrument list, remove support for `seci` being anything other than `False`.
---
=> Type-hint `seci` as `Literal[False]` rather than `bool`. Update HIFI/ARGUS.

BlockServer/core/ioc_control.py
Additional printing to help trace autorestart test failure
=> Add more autorestart printing

BlockServer/runcontrol/runcontrol_manager.py
Move start message so only printed if ioc actually starts
---
=> Move start message to better place

BlockServer/component_switcher/component_switcher.py, BlockServer/core/active_config_holder.py, BlockServer/core/config_list_manager.py, BlockServer/core/macros.py, BlockServer/devices/devices_manager.py, BlockServer/epics/gateway.py, BlockServer/fileIO/file_manager.py, BlockServer/test_modules/test_active_config_holder.py, BlockServer/test_modules/test_component_switcher.py, BlockServer/test_modules/test_config_holder.py, BlockServer/test_modules/test_config_list_manager.py, BlockServer/test_modules/test_configuration.py, BlockServer/test_modules/test_configuration_xml.py, BlockServer/test_modules/test_schema_checker.py, DatabaseServer/test_modules/test_database_server.py, block_server.py, server_common/channel_access.py, server_common/helpers.py, server_common/mocks/mock_procserv_utils.py, server_common/test_modules/test_ioc_data.py
Closes #418 
This removes where `server_common` depends on things like the blockserver, dbserver - it should only be the other way around. 
unit tests pass, blockserver and dbserver still work
see "to test"
---
=> remove server_common dependencies on blockserver and dbserver

start_bs_to_kafka_cmd.bat
This is currently patched on HIFI but we'll lose the change on next deploy, so this needs to be merged before release so we don't have to patch it again.
Check batch logic looks correct. 
---
=> if on HIFI use supermusr redpanda cluster, else use livedata

BlockServerToKafka/block_server_monitor.py, BlockServerToKafka/inst_pvs.py, BlockServerToKafka/main.py, BlockServerToKafka/test_modules/test_inst_pvs.py
Forward the PVs that the inst archiver would have stored, in addition to blocks.
This isn't quite fully equivalent - it doesn't handle archive specifications like `info(archive, "VAL RBV 5.0")` - it always just stores `VAL` on the base PV.
---
=> Forward inst PVs
